In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# **STEP 1: Read and view file**

In [ ]:
API_edu = pd.read_csv(r"/content/drive/My Drive/0. STUDYING Peo Peo/PYTHON/xAPI-Edu-Data.csv")
API_edu.head()

gender NationalITy  ... StudentAbsenceDays Class
0      M          KW  ...            Under-7     M
1      M          KW  ...            Under-7     M
2      M          KW  ...            Above-7     L
3      M          KW  ...            Above-7     L
4      M          KW  ...            Above-7     M

[5 rows x 17 columns]

# **STEP 2: Kiểm tra dữ liệu lỗi**

In [ ]:
API_edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   gender                    480 non-null    object
 1   NationalITy               480 non-null    object
 2   PlaceofBirth              480 non-null    object
 3   StageID                   480 non-null    object
 4   GradeID                   480 non-null    object
 5   SectionID                 480 non-null    object
 6   Topic                     480 non-null    object
 7   Semester                  480 non-null    object
 8   Relation                  480 non-null    object
 9   raisedhands               480 non-null    int64 
 10  VisITedResources          480 non-null    int64 
 11  AnnouncementsView         480 non-null    int64 
 12  Discussion                480 non-null    int64 
 13  ParentAnsweringSurvey     480 non-null    object
 14  ParentschoolSatisfaction  

# **STEP 3**: 
##**1. Tách X va y (dataframe)**

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

# Tạo biến target
y = API_edu['Class']

#  Tập X được chia thành 2 loại:
## Data có dữ liệu là continuous (Dữ liệu chứa số)
X_continuous = API_edu[['Discussion', 'AnnouncementsView', 'VisITedResources', 'raisedhands']]
## Data với dữ liệu là category (Dữ liệu chứa chữ)
X_category = API_edu.drop(['Class', 'Discussion', 'AnnouncementsView', 'VisITedResources', 'raisedhands'], axis = 1)
## Encoding các data
X_category_encode = pd.get_dummies(X_category, prefix_sep='_')
y = le.fit_transform(y)
X = pd.concat([X_continuous, X_category_encode], axis = 1) 

##**2. Train_Test**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, 
                                                    stratify = y, random_state = 0)

#**STEP 4: Choose model**

##**1. Model: Support Vector Machine (SVM)**

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

clf_svm = SVC(kernel = 'poly', C = 10)   
clf_svm.fit(X_train, y_train)

print("Support Vector Machine")
print("\ntrain acc: ", accuracy_score(y_train, clf_svm.predict(X_train)))
print("train acc: ", accuracy_score(y_test, clf_svm.predict(X_test)))
print('\nConfusion matrix : \n', confusion_matrix(y_test, clf_svm.predict(X_test)))
print('Classification report : \n', classification_report(y_test, clf_svm.predict(X_test), digits = 5))

Support Vector Machine

train acc:  0.7202380952380952
train acc:  0.6388888888888888

Confusion matrix : 
 [[19  3 21]
 [ 0 34  4]
 [ 9 15 39]]
Classification report : 
               precision    recall  f1-score   support

           0    0.67857   0.44186   0.53521        43
           1    0.65385   0.89474   0.75556        38
           2    0.60938   0.61905   0.61417        63

    accuracy                        0.63889       144
   macro avg    0.64726   0.65188   0.63498       144
weighted avg    0.64177   0.63889   0.62790       144



#**2. Model: Decision Tree Classifier**


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

print("Decision Tree Classifier")
print("\ntrain acc: ", accuracy_score(y_train, clf.predict(X_train)))
print("train acc: ", accuracy_score(y_test, clf.predict(X_test)))
print('\nConfusion matrix : \n', confusion_matrix(y_test, clf.predict(X_test)))
print('Classification report : \n', classification_report(y_test, clf.predict(X_test), digits = 5))

Decision Tree Classifier

train acc:  1.0
train acc:  0.7777777777777778

Confusion matrix : 
 [[33  0 10]
 [ 0 34  4]
 [ 8 10 45]]
Classification report : 
               precision    recall  f1-score   support

           0    0.80488   0.76744   0.78571        43
           1    0.77273   0.89474   0.82927        38
           2    0.76271   0.71429   0.73770        63

    accuracy                        0.77778       144
   macro avg    0.78011   0.79215   0.78423       144
weighted avg    0.77795   0.77778   0.77620       144



#**3. Model: Random Forest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

clf = RandomForestClassifier()
clf.fit(X_train,y_train)

print("Random Forest Classifier")
print("\ntrain acc: ", accuracy_score(y_train, clf.predict(X_train)))
print("train acc: ", accuracy_score(y_test, clf.predict(X_test)))
print('\nConfusion matrix : \n', confusion_matrix(y_test, clf.predict(X_test)))
print('Classification report : \n', classification_report(y_test, clf.predict(X_test), digits = 5))

Random Forest Classifier

train acc:  1.0
train acc:  0.8125

Confusion matrix : 
 [[35  0  8]
 [ 0 32  6]
 [ 6  7 50]]
Classification report : 
               precision    recall  f1-score   support

           0    0.85366   0.81395   0.83333        43
           1    0.82051   0.84211   0.83117        38
           2    0.78125   0.79365   0.78740        63

    accuracy                        0.81250       144
   macro avg    0.81847   0.81657   0.81730       144
weighted avg    0.81323   0.81250   0.81267       144

