In [1]:

import numpy as np
import math
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
print("X_train")
print(X_train)
print("y_train")
print(y_train)
#'''

X_train
[[4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [6.5 3.2 5.1 2. ]
 [6.7 3.3 5.7 2.1]
 [4.5 2.3 1.3 0.3]
 [6.2 3.4 5.4 2.3]
 [4.9 3.  1.4 0.2]
 [5.7 2.5 5.  2. ]
 [6.9 3.1 5.4 2.1]
 [4.4 3.2 1.3 0.2]
 [5.  3.6 1.4 0.2]
 [7.2 3.  5.8 1.6]
 [5.1 3.5 1.4 0.3]
 [4.4 3.  1.3 0.2]
 [5.4 3.9 1.7 0.4]
 [5.5 2.3 4.  1.3]
 [6.8 3.2 5.9 2.3]
 [7.6 3.  6.6 2.1]
 [5.1 3.5 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.7 2.8 4.5 1.3]
 [6.6 3.  4.4 1.4]
 [5.  3.2 1.2 0.2]
 [5.1 3.3 1.7 0.5]
 [6.4 2.9 4.3 1.3]
 [5.4 3.4 1.5 0.4]
 [7.7 2.6 6.9 2.3]
 [4.9 2.4 3.3 1. ]
 [7.9 3.8 6.4 2. ]
 [6.7 3.1 4.4 1.4]
 [5.2 4.1 1.5 0.1]
 [6.  3.  4.8 1.8]
 [5.8 4.  1.2 0.2]
 [7.7 2.8 6.7 2. ]
 [5.1 3.8 1.5 0.3]
 [4.7 3.2 1.6 0.2]
 [7.4 2.8 6.1 1.9]
 [5.  3.3 1.4 0.2]
 [6.3 3.4 5.6 2.4]
 [5.

In [2]:
'''
import numpy as np
import math
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB, MultinomialNB
rng = np.random.RandomState(42)
nPond = 20
nFeature = 100
nTest = 5
X_train = rng.randint(5, size=(nPond, nFeature))
y_train = rng.randint(5,size=nPond)
X_test = rng.randint(3, size=(nTest,nFeature))
'''

'\nimport numpy as np\nimport math\nfrom sklearn.naive_bayes import MultinomialNB\nfrom sklearn.naive_bayes import GaussianNB, MultinomialNB\nrng = np.random.RandomState(42)\nnPond = 20\nnFeature = 100\nnTest = 5\nX_train = rng.randint(5, size=(nPond, nFeature))\ny_train = rng.randint(5,size=nPond)\nX_test = rng.randint(3, size=(nTest,nFeature))\n'

In [3]:
print("Class and count: ")
Class,Count = np.unique(y_train, return_counts = True)
print(Class)
print(Count)

Class and count: 
[0 1 2]
[29 20 26]


In [4]:
'''
function: GaussCalc
Purpose: Calculation log P(value of feature kth|class) by gauss
Input:
  - X: train set data
  - y: train set class
  - Class: array of name class
  - k: feature kth
  - value: value to calculation
  - c: index class in Class array
Output: Result log P(value of feature kth|class) by gauss
'''
def GaussCalc(X,y,Class,k,value,c):
  #Get feature of class Class[c]
  feature_c = []
  for i in range(X_train.shape[0]):
    if (y[i] == Class[c]):
      feature_c.append(X_train[i][k]);
  #print(feature_c)
  # Calculation EX and VAR
  EX = 0
  EX2 = 0
  VAR = 0
  for i in range(len(feature_c)):
    EX = EX + feature_c[i]
    EX2 = EX2 + pow(feature_c[i],2)
  EX = EX / len(feature_c)
  EX2 = EX2 / len(feature_c)
  VAR = EX2-pow(EX,2)
  if (VAR==0):
    VAR = 1e-9
  #print(EX)
  #print(VAR)
  #print(value)
  # caculation result
  res = -math.log(math.sqrt(2*math.pi*VAR))-pow(value-EX,2)/(2*VAR)
  return res

In [5]:
y_pred = []
for i in range(len(X_test)):
  max_value_C = -100000000
  max_position = -1
  for j in range(len(Class)): # c = Class[i]
    # tinh argmax p(c|X_test[i]) = argmax p(X_test[i]|c)*p(c) = argmax ln(p(X_test[i]|c))+argmax(p(c))
    p_c = math.log(Count[j]/len(y_train))
    #tinh argmax p(X_test[i]|c) = argmax product(p(X_test[i][j]|c)) = argmax sum ln(p(X_test[i][j]|c))
    product = 0;
    for k in range(X_train.shape[1]):
      product = product + GaussCalc(X_train,y_train,Class,k,X_test[i][k],j)
    value_C = p_c+product
    if (value_C> max_value_C):
      max_value_C = value_C
      max_position = j
  y_pred.append(Class[max_position])

In [6]:
print("Self Build model:")
print(y_pred)
#print(accuracy_score(y_test,y_pred))

Self Build model:
[2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1]


In [7]:
print("Sklearn GaussianNB:")
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print(y_pred)
#print(accuracy_score(y_test,y_pred))

Sklearn GaussianNB:
[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1 1 2 1 1 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0
 1]
